### PR TITLE
update masthead illustration

### LINKED ISSUE #17: Update masthead illustration
@QAI.help Current illustration:

image

Desired illustration (from https://docs.google.com/presentation/d/10eFiKwqTu2kKYc8-5aXNObcSRC3Dsi34zvuSF59X9B0):
image

This task involves:
1. Adding the relevant .svg files (see https://thenounproject.com/search/icons/?iconspage=1&q=artificial%20intelligence and https://www.vecteezy.com/free-vector/ai-icon)
2. Displaying them as in https://github.com/OpenAdaptAI/web/blob/main/components/MastHead.js#L47
3. Adding subtle animations as in https://github.com/OpenAdaptAI/web/blob/main/components/MastHead.js#L24

### PR DESCRIPTION
**Pull request by jesicasusanto**
This PR resolves #17 . This PR updates the masthead illustration to be the desired illustration.

Before : 

image

After :

image

### CODE REVIEW

**Comment by abrichr** [comment]
Thanks @jesicasusanto ! Here is what I see at https://deploy-preview-20--cosmic-klepon-3c693c.netlify.app/:

image

If this is a draft can you please mark it as such? 🙏

**Comment by jesicasusanto** [comment]
@abrichr yes, done!

**Comment by jesicasusanto** [comment]
Hi @abrichr , this PR is ready for review. Thank you!

**Comment by jesicasusanto** [comment]
I added left margin to the icon to center it above the box (https://github.com/OpenAdaptAI/web/pull/20/commits/7c44b96c0a620e625790d6acbf2efa9d6cc19088) @abrichr  Please let me know what you think. thank you.

Before
image
After
image

**Pull request closed without merging**
